"""Frame assembly and parsing.

Frame layout (every field is a bit sequence)::

    Preamble (64) | Original Length (32) | Coded Length (32)
    | Coded Payload (N) | CRC-32 (32)

- **Original Length** – number of information bits before scrambling.
- **Coded Length**  – number of bits after channel encoding (= payload in frame).
- **CRC-32**        – computed over the *original* information bits (``zlib.crc32``).

Two calling conventions for ``build_frame``:

``build_frame(payload)``
    Payload is treated as both original and coded (no built-in encoding).
``build_frame(original, coded)``
    CRC covers *original*; *coded* is stored in the frame.
"""

import zlib

#: 64-bit preamble generated by a 7-bit maximal-length LFSR
#: (polynomial x^7 + x^6 + 1, initial state 0b1010111).
_PREAMBLE_BITS = [
    1, 1, 1, 0, 1, 0, 1, 0,
    0, 1, 1, 0, 0, 1, 0, 0,
    0, 0, 1, 1, 1, 1, 0, 0,
    1, 0, 1, 1, 0, 1, 1, 0,
    1, 0, 0, 1, 0, 0, 0, 1,
    0, 1, 0, 1, 1, 1, 1, 0,
    1, 1, 0, 0, 1, 1, 0, 0,
    0, 1, 1, 1, 0, 1, 1, 1,
]

#: Minimum frame length in bits (preamble + orig_len + coded_len + CRC, no payload).
_MIN_FRAME_BITS = 64 + 32 + 32 + 32


def _bits_to_bytes(bits: list[int]) -> bytes:
    """Pack MSB-first bits into bytes.

    Args:
        bits: Bit list whose length must be a multiple of 8.

    Returns:
        Packed bytes.

    Raises:
        AssertionError: If ``len(bits)`` is not divisible by 8.
    """
    bit_ints = [int(b) for b in bits]
    assert len(bit_ints) % 8 == 0
    data = bytearray()
    for i in range(0, len(bit_ints), 8):
        val = 0
        for j in range(8):
            val = (val << 1) | bit_ints[i + j]
        data.append(val)
    return bytes(data)


def _compute_crc32(bits: list[int]) -> int:
    """Compute CRC-32 (IEEE 802.3 / zlib) over a MSB-first bitstream.

    Non-byte-aligned streams are zero-padded to the next byte boundary before
    the CRC is calculated.  The result is masked to an unsigned 32-bit integer.

    Args:
        bits: Payload bit list (may be empty or non-byte-aligned).

    Returns:
        Unsigned 32-bit CRC value.
    """
    if len(bits) == 0:
        return zlib.crc32(b"") & 0xFFFFFFFF
    if len(bits) % 8 != 0:
        pad = (8 - len(bits) % 8) % 8
        bits = list(bits) + [0] * pad
    return zlib.crc32(_bits_to_bytes(bits)) & 0xFFFFFFFF


def _int_to_bits_be(value: int, width: int) -> list[int]:
    """Encode a non-negative integer as *width* big-endian bits."""
    return [(value >> i) & 1 for i in range(width - 1, -1, -1)]


def _bits_to_int_be(bits: list[int]) -> int:
    """Decode a big-endian bit list into an integer."""
    val = 0
    for b in bits:
        val = (val << 1) | int(b)
    return val


def build_frame(original_payload_bits: list[int],
                coded_payload_bits: list[int] | None = None,
                seed: int = 2026) -> list[int]:
    """Assemble the complete frame bitstream.

    Args:
        original_payload_bits: Information bits (before scramble).
        coded_payload_bits: Channel-encoded bits.  When *None*, the
            one-argument shorthand is used and the payload is stored as-is.
        seed: Reserved for future use (currently unused inside this function).

    Returns:
        Flat list of frame bits.
    """
    original = [int(b) for b in original_payload_bits]
    coded = original if coded_payload_bits is None else \
            [int(b) for b in coded_payload_bits]

    preamble = list(_PREAMBLE_BITS)
    orig_len_bits = _int_to_bits_be(len(original), 32)
    coded_len_bits = _int_to_bits_be(len(coded), 32)
    crc_bits = _int_to_bits_be(_compute_crc32(original), 32)

    return preamble + orig_len_bits + coded_len_bits + coded + crc_bits


def parse_frame(frame_bits: list[int],
                preamble: list[int] | None = None) -> dict:
    """Extract every field from a serialised frame.

    Validates minimum frame length, coded-length bounds, and CRC presence.
    When *preamble* is provided the received preamble is verified against it.

    Args:
        frame_bits: Received frame bitstream.
        preamble: Optional reference preamble for verification.

    Returns:
        ``{"preamble", "original_length", "coded_length", "payload",
        "coded_payload", "crc_received", "length"}``.

    Raises:
        ValueError: If the frame is too short, has inconsistent lengths,
            or is otherwise structurally invalid.
    """
    bits = [int(b) for b in frame_bits]

    if len(bits) < _MIN_FRAME_BITS:
        raise ValueError(
            f"Frame too short: {len(bits)} bits < {_MIN_FRAME_BITS} minimum"
        )

    offset = 0
    read_preamble = bits[offset:offset + 64]
    offset += 64

    # Verify preamble when reference is supplied
    if preamble is not None:
        ref = [int(b) for b in preamble]
        if len(ref) != 64:
            raise ValueError(f"Reference preamble must be 64 bits, got {len(ref)}")
        if read_preamble != ref:
            raise ValueError("Received preamble does not match reference preamble")

    original_length = _bits_to_int_be(bits[offset:offset + 32])
    offset += 32

    if original_length < 0:
        raise ValueError(f"Original length overflow (treated as negative)")

    coded_length = _bits_to_int_be(bits[offset:offset + 32])
    offset += 32

    if coded_length < 0:
        raise ValueError(f"Coded length overflow (treated as negative)")

    # Validate that both coded payload AND 32-bit CRC fit in the remaining bits.
    remaining = len(bits) - offset
    if coded_length + 32 > remaining:
        if coded_length > remaining:
            raise ValueError(
                f"Coded length {coded_length} exceeds remaining frame bits "
                f"({remaining})"
            )
        else:
            raise ValueError(
                "CRC field truncated: not enough bits remaining "
                f"(need 32, have {remaining - coded_length})"
            )

    coded_payload = bits[offset:offset + coded_length]
    offset += coded_length

    crc_received = bits[offset:offset + 32]

    return {
        "preamble": read_preamble,
        "original_length": original_length,
        "coded_length": coded_length,
        "payload": coded_payload,
        "coded_payload": coded_payload,
        "crc_received": crc_received,
        "length": original_length,
    }
